# Generated by Django 4.1.6 on 2023-02-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur')),
            ],
            options={
                'ordering': ['id'],
                'permissions': [('peut_voir', 'Peut voir le trouv, indépendamment de son produit'), ('peut_modifier_trouv', 'Peut modifier le trouv.'), ('peut_supprimer_trouv', 'Peut supprimer le trouv.')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trouv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvs.trouv')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='trouv',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='trouvs.Vote', to='utilisateurs.utilisateur'),
        ),
        migrations.CreateModel(
            name='FichiersTrouv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='fichiers')),
                ('trouv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouvs.trouv')),
            ],
        ),
    ]
