# Generated by Django 4.1.6 on 2023-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_options_alter_utilisateur_table'),
        ('trouvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fichierstrouv',
            unique_together={('trouv', 'fichier')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('utilisateur', 'trouv')},
        ),
        migrations.AlterModelTable(
            name='fichierstrouv',
            table='fichiers_trouv',
        ),
        migrations.AlterModelTable(
            name='trouv',
            table='trouvs',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='votes',
        ),
    ]
