# Generated by Django 4.1.6 on 2023-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvs', '0002_alter_fichierstrouv_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouv',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
    ]
