# Generated by Django 4.1.6 on 2023-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouvs', '0003_trouv_no_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='valeur',
            field=models.IntegerField(default=0),
        ),
    ]
