# Generated by Django 4.1.6 on 2023-02-15 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='pdp')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='banniere')),
                ('datecrea', models.DateTimeField(auto_now_add=True)),
                ('datemodif', models.DateTimeField(auto_now=True, null=True)),
                ('datesupp', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'permissions': [('peut_voir_trouvs_global', 'Peut voir tous les trouvs du produit, indépéndamment du suivi de leur produit.'), ('peut_creer_trouvs_global', 'Peut créer des les trouvs pour tous les produits, indépendamment de leur suivi.'), ('peut_modifier_trouvs_global', "Peut modifier n'importe quel trouv."), ('peut_supprimer_trouvs_global', "Peut supprimer n'importe quel trouv."), ('peut_voir_produits_global', 'Peut voir tous les produits, indépendamment de leur suivi.'), ('peut_creer_produits_global', 'Peut créer des produits.'), ('peut_modifier_produits_global', "Peut modifier n'importe quel produit."), ('peut_supprimer_produits_global', "Peut supprimer n'importe quel produit."), ('peut_voir_utilisateurs_global', 'Peut voir tous les utilisateurs.'), ('peut_creer_utilisateurs_global', 'Peut créer des utilisateurs sur la plateforme admin.'), ('peut_modifier_utilisateurs_global', "Peut modifier n'importe quel utilisateur."), ('peut_supprimer_utilisateurs_global', "Peut supprimer ,'importe quel utilisateur.")],
            },
        ),
    ]
