# Generated by Django 4.1.6 on 2023-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['user'], 'permissions': [('peut_voir_trouvs_global', 'Peut voir tous les trouvs du produit, indépéndamment du suivi de leur produit.'), ('peut_creer_trouvs_global', 'Peut créer des trouvs pour tous les produits, indépendamment de leur suivi.'), ('peut_modifier_trouvs_global', "Peut modifier n'importe quel trouv."), ('peut_supprimer_trouvs_global', "Peut supprimer n'importe quel trouv."), ('peut_voir_produits_global', 'Peut voir tous les produits, indépendamment de leur suivi.'), ('peut_creer_produits_global', 'Peut créer des produits.'), ('peut_modifier_produits_global', "Peut modifier n'importe quel produit."), ('peut_supprimer_produits_global', "Peut supprimer n'importe quel produit."), ('peut_voir_utilisateurs_global', 'Peut voir tous les utilisateurs.'), ('peut_creer_utilisateurs_global', 'Peut créer des utilisateurs sur la plateforme admin.'), ('peut_modifier_utilisateurs_global', "Peut modifier n'importe quel utilisateur."), ('peut_supprimer_utilisateurs_global', "Peut supprimer ,'importe quel utilisateur.")]},
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateurs',
        ),
    ]
