# Generated by Django 4.1.6 on 2023-05-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_options_alter_utilisateur_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='photo_de_profil',
        ),
    ]
