# Generated by Django 4.1.6 on 2023-06-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_utilisateur_photo_de_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='datecrea',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='datemodif',
            new_name='date_modification',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='datesupp',
            new_name='date_suppresion',
        ),
    ]
