# Generated by Django 4.1.6 on 2023-06-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_rename_datecrea_utilisateur_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='date_suppresion',
            new_name='date_suppression',
        ),
    ]
