# Generated by Django 4.1.6 on 2023-02-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'permissions': [('peut_voir_trouvs', 'Peut voir tous les trouvs du produit'), ('peut_creer_trouvs', 'Peut créer des les trouvs pour le produit'), ('peut_modifier_trouvs', 'Peut modifier les trouvs du produit'), ('peut_supprimer_trouvs', 'Peut supprimer les trouvs du produit'), ('peut_voir_produit', 'Peut voir le produit'), ('peut_creer_produit', 'Peut créer le produit'), ('peut_modifier_produit', 'Peut modifier le produit'), ('peut_supprimer_produit', 'Peut supprimer le produit')],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('photo_de_profil', models.ImageField(blank=True, null=True, upload_to='pdp')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='banniere')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
                ('date_suppresion', models.DateTimeField(blank=True, null=True)),
                ('utilisateurs_abonnes', models.ManyToManyField(through='produits.AccesProduit', to='utilisateurs.utilisateur')),
            ],
            options={
                'ordering': ['nom'],
                'permissions': [('peut_voir_trouvs', 'Peut voir tous les trouvs du produit'), ('peut__produits', 'Peut controller tous les produits')],
            },
        ),
        migrations.AddField(
            model_name='accesproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='accesproduit',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.roleproduit'),
        ),
        migrations.AddField(
            model_name='accesproduit',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur'),
        ),
    ]
