# Generated by Django 4.1.6 on 2023-05-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_alter_roleproduit_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['nom'], 'permissions': [('peut_voir_trouvs', 'Peut voir tous les trouvs du produit')]},
        ),
    ]
